sudo: false
language: java
notifications:
  email: false
  on_failure: always                                                                                                                            
  on_success: change
  pushover:
    api_key:
      secure: cOz6J3l37jvUY7Rapomu0j+c0HAKRnfTYxIVLQwzHv3fEYIzaB9wQQwdZabuRXo5KPLlgaXPG3nKTeEwRCzsnFfBXMyADutEoaNMf0Sz3PzUQ+mRWI5APfJCkLJvB6IBuQYCThcuG+euseb4jy+1CsLNEWrQztDNAOUZnY9LyhGKnhNlm0Y07cVHkevFWSIJ2LL1WMSUvmSLzBpzeEaXFeLSnwTXmOJxFLbrfqOhoepK0QVBcULEX5oNnxMGepw9sWLHBCGcde4KCgZ5mAryUgNO+pWp+FmcbrL1K1eRP2tRe7/yLvlhklIgRN8sipeZdrL7s9oiv7ZXHZTa2eiYbHPyceYo2mGpr37MVuGu/udALFfJ4BAXrQoG95i7wk4vhfnNvRIo+Bq7v37DBgmSREbgOQPfw9q4No2i3FtnTI0XuDlVTyI9LSbRgMZ4XD6PrROH04Xkuy4Rwz4eeQklPi/IgV85aMOIv/JrfD8kgXWEij2QnrLjHl0tHfODS2AIpb3po8oTCJuSuPCY/p956XNoxLVl4EvfEV3vgz6HLcOMmCFaMBUOMuo/xE/exZZCnOhLnIizjLetVKeTsrRx7AIZakBFUHTJSpSBcPPi9+k2gY8irc6aKyvaJyDXRlUlNiQ4BatUks7OFC+6hb6Np5r1KeFAjbB+fQrQ9mGJqtU=
    users:
      - secure: uqag/MZUNDDJp4W+iFf6X9ErJde2dvNoJVDV4mlMrFKohIxqir0MXKQa4G8bCU4bl9I7XZIwbhs5nI3sXtqsoO3CuQ564abKJyh7VnShKnJuc3Tw8iJjCUJHYVvg7Ic5gzyy0MdRuKcrqOzeE5Zc8V0UHS0HkBZ5wtICP4AfWl/5YP71vDFR6dQH+tVCscfsESRUaCY9YjxZ6OnSugimnwHKL01N42BtaSQL8unWpw7Lrqe0YLJ29YY5UxDvS6uwyhGuG2pL2uUtNttXdUKnEK4/rIJNB0g4656FbGiWXxBzh+hUWx5QSmvXlUoqCEfAKYE84n9h1EWegh+0uNuYc+S5cDV3rcKv23uKq4PwQyMSu2AVSMoXuVP1P7wcFb8N/IRiZcz8tZ8WEpu2Grac+MNuzojKdiMwgRn6NPDkqJ11jQYuJ8+9yca4I1UdAwHHvXDd3AaxEYlG3gKn4j03SnZfahKXhx8kRk+2zeR5UiLbQLBYCASsPuPjkK2K7c5Gi6LlOiZShb5aqg3aJcvzAd+/R8Mm/ZuCA3P4GMksMHxz4qN/h/t6GtQWUaPGTW0SZTjOrTpS7spnHF1lZgoMWLbK47xwZRrPg+hL9hyWteH1nIL3kQdRWF0TV5R34NQd91POaukFvSs5yuL2+kdiXl28Iko64BvLWsAPpxuh13U=
addons:
  artifacts:
    branch:
      - master
    bucket: ceylon.vasileff.com
    target_paths: modules
    paths:
      - ./modules
    key:
      secure: nH9onF834lLmDOpPz/mnbIDYOOTG+/GT+8hc4oYV4GDx2HIYrlIsz8GB6iUf8+Ael+53OR8BC6kG0H5OSFQJP3kPfnOvNZd+a52feULfTUpgcCvFupf/RRZS9uDVG1C1khTmlfayFAlggkpmg9ziW7D8KKGKZmSGgLcZ7yqgwRUDsitRNUwvRw+TN9v2GIirHhwAvfhIqEhHJ/7kgNu3CWJfbJEWHVgAGuNHp7zyI3p1lJIRk5So+wYOYKC4w03DCIXSObeItgcXh01y/lItsQLUkuxOVa6yqEO0aqmpc164Z4fuOgq9NYXyQZNn/J+kds4bg4VkpAXK3qVgSn0ta/YlQvsjVBK06MQ97VyNFRGXGWDkssAtdB1bjYo7YHpkf6y861YhAsl3uhObPeEUrhoi5ZKodcKviT+V75SLudkZTF9hVk5I2dCbrPM71RzuVaEjFQBHnSdGLfRxVHtDqIGsQHX99tlS4u/IGjaDzZAw9sj/0O6NsOfttznkdHC1be+nG63DlW4F+Bpk3IZ6WE9qlwH6pVAhg94DS+21+icQAuBukudWJxRAH8rRKAxBOWPRWwSFNuNKywo8BFqRsgCxBhU8jqoDYYihxrnoBnFwNAM5/N+E2NFsYqxKFuqTGX3Y/9eFsdLOa6bI4gnUeBTY94XWTXAqhAjea5gIKm8=
    secret:
      secure: lJ1+aI8t/JWIxZ6O1qwCv5RMdSknHfarsiOCMMiSVyTrrSX7HnYESEA61gx99R578DtV79c3uDUfLjwL9e3SIutIDRd2jaMUd+BXBsoDmWF+lvI8A/X5/7KC77aavpqx8imi5MLs8TUvfFymeT2cgqAlotwO9Kpkbc0QL1kHPgGTnD+sN5Md6QxTlXYuSVzCpx73NDs+41AEWRRT/VrjECeWqLcbjYWB6cNNiNzIODER/wU0/IqQI6svbjYX84TU+dNqZQzLX4RAwK1uX958NC4pKTbvj19Fj7qt+I3kpQjEyYLiYV8XnLNt53vWrj6PC0S+ca8CQBx7f0cJtUgy/+S29kQxSpVnSd7gZmLSg03cDTn5rXZ/yi4WkL22Q1tfvDyvopWHziL4l8mGZjIdErqu6P2IsBv8K/OCgZbp5k9yeLSkbyQFCrOJf7DtYnfaSIJ5lw+zLZU9p+iUpH9+2d4U8DJrzi10c8HkcYGeWf9pAPdaZ076xQQlKj6lotLy87CoAqEUpgTvGyV+CS8Hw/T/cNLmjMrMSm8KraQQEn+3AdlpK0ncRD29aR0Dh3EN5vrYWR+7VbBJoU4n9SVcjPa7yUNNc6Jx6FFGyqD6mA6NlQTg5OO9LDxl+zr2sRkFHOfen+IBdSj/adwFUYRRp9is3/N/KwwDyBajPjHlxco=
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/archive.zip "$CEYLON_DIST"
  - unzip -q /tmp/archive.zip
  - unzip -q $PWD/archive/ceylon/dist/ceylon-1.3.3-SNAPSHOT*.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.3-SNAPSHOT/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.3-SNAPSHOT
  - wget --quiet --output-document=/tmp/sdk.zip "$CEYLON_SDK"
  - unzip -q /tmp/sdk.zip
  - echo -e "\n[repository \"sdk\"]\nurl=$PWD/archive/modules\n[repositories]\nlookup=modules\nlookup=+sdk" >> $TRAVIS_BUILD_DIR/.ceylon/config
  - ceylon --version
script:
  - ceylon compile,compile-js
  - ceylon doc --source-code
env:
  global:
    - CEYLON_DIST="https://ci-ceylon.rhcloud.com/job/ceylon-distribution/lastSuccessfulBuild/artifact/*zip*/archive.zip"
    - CEYLON_SDK="https://ci-ceylon.rhcloud.com/job/ceylon-sdk/lastSuccessfulBuild/artifact/*zip*/archive.zip"

